### ISSUE TITLE
Kapitel Statische Magnetfelder 

### ISSUE THREAD

**Issue by nadine0207** [etschgi1/Ex2_Fragen#21]
Frage 4:
Schreiben Sie eine Ausdruck für das Magnetfeld zweier paralleler, stromdurchflossener,
zylindrischer Leiter an. Erstellen Sie ein Diagramm der magnetischen Feldstärke als Funktion
des Ortes entlang einer Linie, die die Achsen beider Leiter unter 90° schneidet. Welche
Richtung hat das Magnetfeld entlang dieser Linie? 

Da ist die Kraft und nicht das Magnetfeld berechnet worden (einfach mit B = B1 + B2 und da halt das für den Leiter einsetzen)

Außerdem fehlt das Diagramm:
Wenn im Diagramm positiv zeigen die Magnetfeldlinien  nach oben, wenn negativ zeigen sie nach unten

(hoffe das Bild funktioniert, sonst: https://www.ate.uni-due.de/data/get12/GET1_4_Magnetfeld_HO.pdf (PDF-Seite 20)
![image](https://user-images.githubusercontent.com/86371023/123133067-a8893000-d44f-11eb-85b8-015a6ac08aff.png)

**Comment by nadine0207** [comment]
und bei Frage 5:
Da fehlt glaube ich noch bei welchem Winkel der magn. Fluss am stärksten ist.
(Glaube wenn Flächennormale A parallel zu B)

**Comment by etschgi1** [comment]
Super danke, werden wir natürlich zeitnah ausbessern.
