### ISSUE TITLE
13 Elektromagnetische Wellen

### ISSUE THREAD

**Issue by nadine0207** [etschgi1/Ex2_Fragen#26]
Ich bin mir nicht ganz sicher ob das so nicht eh stimmt, aber bei Frage 1 hätte ich den Ausdruck für E, also E = E_0 * exp(i(kr - wt)) und das mit Sinus von der zweiten Frage dazu geschrieben. 

Und bei der zweiten Frage glaube ich, dass da die Wellengleichung gefragt ist (die momentan in der 1. Frage steht). Außerdem fehlt da der Zusammenhang zwischen der Gleichung und T bzw. lambda -> lambda = c*T  

Wie gesagt bin ich mir selbst nicht 100% sicher dabei ^^'

**Comment by etschgi1** [comment]
Ich hab mir das jetzt angeschaut und die vorgeschlagenen Ergänzungen eingefügt. Sollte jetzt etwas besser auf die Frage eingehen. 
Bin mir dabei aber selbst etwas unsicher!
