### ISSUE TITLE
[Fehler]: <Grobe Beschreibung einfügen>

### ISSUE THREAD

**Issue by nadine0207** [etschgi1/Ex2_Fragen#27]
Thematischer Fehler in Kapitel 13

Ist (beschreibt den jetzigen Zustand):
I = c \epsilon _0 E_0^2

Soll (beschreibt den soll-Zustand nach dem Fix):
I = 1/2 c \epsilon _0 E_0^2

<Sonstige Anmerkungen einfügen>
![image](https://user-images.githubusercontent.com/86371023/123483243-b59c4f80-d606-11eb-9a2f-fd39723b496e.png)

**Comment by zandivx** [comment]
Danke, ist ausgebessert!
